SAVE_FOLDER = "demo_movie_reviews_link"
MONGODB_CLUSTER = "mongodb+srv://imdb_adt:imdb_adt@cluster0.rcvxgzc.mongodb.net/"
# MONGODB_CLUSTER = "mongodb+srv://astmohap:athe@astmohap.jojxwas.mongodb.net/"
DATABASE_NAME = "Moviedatabase"
COLLECTION_NAME = "moviedata"
WIKIPEDIA_FOLDER = "wikipedia_data"
VECTORDB_COLLECTION_NAME = "moviedata_vectordb"
ATLAS_VECTOR_SEARCH_INDEX_NAME = "EmbeddingText"
