SAVE_FOLDER = "movie_reviews_link"
MONGODB_CLUSTER = "mongodb+srv://imdb_adt:imdb_adt@cluster0.rcvxgzc.mongodb.net/"
DATABASE_NAME = "Moviedatabase"
COLLECTION_NAME = "moviedata"
WIKIPEDIA_FOLDER = "wikipedia_data"
